local w0 = {
    'å', '∫', 'ç', '∂', '´', 'ƒ', '©', '˙', 'ˆ', '∆', '˚', '¬',
    'µ', '˜', 'ø', 'π', 'œ', '®', 'ß', '†', '¨', '√', '∑', '≈',
    '¥', "Í", "□", "À", "�", "℮", "╤", "ф", "Ð", "ñ", "Ћ", "Ç",
    "ƒ", "Ё", "ê", "№", "Ä", "•", "à", "ü"
}

local w1 = {

    "•0", "•3•", "'", "63636", "20", "0•", "'ƒ", "•Ð", "ÇÍ", "2'",
    "00", "2Ð", "665G", "979", "Ä2", "•Ç", "3À", "Ç•", "ÇÇ", "Ç1T",
    "ƒb", "Ç•AG3", "Ç•ÇL", "Í•1", "Í•3", "ƒÇ12", "ƒÇ•1",
    "ƒÇ•2", "Ç1b", "Ç•ÇB", "№2", "№z", "•5", "22", "you’re",
    "À5G", "Äà", "I'm", "'Ç", "'Ð"
}

local w2 = {
    'zn', 'ok', 'ol', 'ac', 'ne', 'nd', 'nb', 'om', 'on', 'na', 'np', 'mw',
    'mv', 'op', 'or', 'mu', 'mt', 'ms', 'mr', 'mp', 'za', 'nr', 'xx', 'xw',
    'xu', 'xs', 'xr', 'os', 'ot', 'xi', 'xd', 'xc', 'mo', 'mn', 'mm', 'ml',
    'mk', 'ns', 'wu', 'wt', 'ws', 'ow', 'ad', 'ox', 'oz', 'nt', 'pa', 'my',
    'mi', 'mh', 'mg', 'mf', 'wr', 'me', 'md', 'mc', 'mb', 'pc', 'pd', 'pe',
    'ae', 'ma', 'nu', 'lx', 'af', 'lv', 'wo', 'wm', 'wl', 'wk', 'lu', 'lt',
    'ls', 'lr', 'lp', 'ag', 'pf', 'pg', 'ph', 'lo', 'ln', 'lm', 'll', 'pi',
    'ly', 'li', 'lh', 'lg', 'lf', 'ah', 'ai', 'ay', 'ak', 'le', 'ld', 'lc',
    'lb', 'al', 'la', 'zs', 'kw', 'kv', 'kt', 'pk', 'pl', 'kr', 'ko', 'kn',
    'km', 'kl', 'ky', 'ki', 'kg', 'wy', 'wi', 'kc', 'kb', 'ka', 'nv', 'ju',
    'jt', 'js', 'jr', 'jo', 'ji', 'jg', 'am', 'pm', 'po', 'ja', 'bk', 'ix',
    'iw', 'iv', 'yt', 'it', 'ys', 'is', 'yr', 'ir', 'iq', 'wh', 'wg', 'wf',
    'yo', 'io', 'pp', 'pq', 'pr', 'ps', 'pt', 'pu', 'an', 'ob', 'qe', 'qh',
    'qy', 'ql', 'qm', 'qn', 'qp', 'qr', 'qs', 'qt', 'qu', 'yn', 'in', 'we',
    'wd', 'wc', 'wb', 'qv', 'no', 'ra', 'ym', 'im', 'il', 'ik', 'yi', 'ii',
    'if', 'ye', 'ie', 'yd', 'id', 'ic', 'ib', 'ya', 'ia', 'nm', 'nl', 'hw',
    'hv', 'hu', 'ht', 'hs', 'hr', 'hq', 'hp', 'rc', 'ab', 're', 'ho', 'hm',
    'hl', 'hy', 'hi', 'hg', 'hf', 'aa', 'he', 'hd', 'hb', 'wa', 'nj', 'vv',
    'vu', 'vt', 'vs', 'vr', 'vp', 'rf', 'rg', 'rh', 'vo', 'vl', 'ha', 'oc',
    'gv', 'gu', 'gt', 'gs', 'rm', 'rn', 'ro', 'gr', 'gp', 'ao', 'ap', 'go',
    'gn', 'gm', 'vi', 'vg', 'gl', 'rs', 'rt', 'gi', 'ny', 'sa', 'ge', 'gd',
    'aq', 'ar', 'ga', 'ni', 'fz', 'fw', 'fv', 'fu', 'ft', 'fs', 'vd', 'vc',
    'vb', 'fr', 'fp', 'sb', 'sc', 'fo', 'fn', 'fm', 'fl', 'fy', 'fi', 'fg',
    'ff', 'sd', 'se', 'fe', 'fc', 'fb', 'va', 'ng', 'ux', 'fa', 'od', 'as',
    'ex', 'ew', 'sf', 'ut', 'sg', 'sh', 'eu', 'et', 'es', 'us', 'er', 'eq',
    'ep', 'eo', 'si', 'at', 'en', 'ur', 'em', 'sk', 'el', 'ey', 'eh', 'eg',
    'sl', 'ef', 'ee', 'ed', 'ec', 'ea', 'oe', 'dz', 'dx', 'du', 'dt', 'ds',
    'sm', 'dr', 'dp', 'up', 'sn', 'do', 'dn', 'dm', 'dl', 'dk', 'dj', 'av',
    'so', 'aw', 'ax', 'sp', 'az', 'of', 'ba', 'dy', 'di', 'dg', 'sq', 'sr',
    'ss', 'st', 'su', 'de', 'dd', 'dc', 'db', 'da', 'og', 'cv', 'cu', 'ct',
    'cs', 'cr', 'cq', 'cp', 'sv', 'sw', 'oh', 'ta', 'tb', 'tc', 'td', 'te',
    'bb', 'bd', 'tg', 'be', 'th', 'co', 'cm', 'ti', 'cl', 'ck', 'tk', 'tm',
    'tn', 'to', 'cy', 'tp', 'tr', 'ch', 'cg', 'cf', 'ce', 'cd', 'cc', 'cb',
    'ts', 'tu', 'tv', 'tx', 'oy', 'uc', 'ud', 'ug', 'uh', 'ui', 'um', 'un',
    'ca', 'zo', 'bz', 'bx', 'bv', 'bf', 'bg', 'bi', 'by', 'bu', 'bt', 'bs',
    'br', 'bp', 'bo', 'bn', 'bm', 'bl', 'rd'
}

local w3 = {
    'aeq', 'aer', 'pen', 'mal', 'won', 'may', 'mah', 'pep', 'per', 'mag', 'mae',
    'wok', 'woy', 'aes', 'wog', 'mad', 'woe', 'aet', 'wod', 'mac', 'mab', 'oct',
    'noo', 'lxx', 'oda', 'wob', 'lwp', 'odd', 'lwo', 'lwm', 'afb', 'afd', 'lwl',
    'ode', 'aff', 'lux', 'lut', 'woa', 'ods', 'wmk', 'odz', 'nub', 'net', 'wjc',
    'lur', 'luo', 'wiz', 'lum', 'lui', 'lug', 'lue', 'lud', 'luc', 'lub', 'abs',
    'ltr', 'oer', 'lst', 'lsc', 'oes', 'abb', 'lpm', 'off', 'lox', 'pes', 'low',
    'lou', 'lot', 'aft', 'pet', 'lor', 'loq', 'lop', 'wit', 'loo', 'nep', 'aga',
    'loy', 'pew', 'log', 'lof', 'loe', 'lod', 'ofo', 'pfc', 'pfd', 'pfg', 'pfx',
    'oft', 'nul', 'age', 'loc', 'lob', 'loa', 'num', 'lnr', 'zod', 'ohm', 'llb',
    'oho', 'liz', 'wis', 'liv', 'phi', 'wir', 'lit', 'agy', 'lys', 'lis', 'lir',
    'liq', 'lip', 'pho', 'lyn', 'lin', 'ago', 'phr', 'lym', 'lim', 'pht', 'agr',
    'phu', 'ohs', 'pia', 'pya', 'lig', 'lif', 'pic', 'lye', 'lie', 'lid', 'lyc',
    'lib', 'agt', 'ohv', 'nor', 'lhd', 'lhb', 'oie', 'zoa', 'abc', 'lex', 'abd',
    'aha', 'lew', 'ahi', 'aho', 'ahs', 'aht', 'ahu', 'lev', 'pie', 'oii', 'oik',
    'pye', 'aid', 'aye', 'leu', 'pig', 'aik', 'let', 'ail', 'les', 'ler', 'aim',
    'pik', 'ain', 'air', 'pil', 'lep', 'leo', 'len', 'lek', 'ley', 'lei', 'pim',
    'leg', 'lee', 'ais', 'ays', 'led', 'pin', 'ait', 'ayu', 'aix', 'neo', 'aka',
    'lea', 'oil', 'ake', 'ldg', 'nek', 'lcm', 'lcd', 'lca', 'zit', 'lbw', 'lbs',
    'lbf', 'nei', 'laz', 'lax', 'law', 'ako', 'lav', 'aku', 'nun', 'ala', 'lat',
    'las', 'pip', 'lar', 'alb', 'lap', 'lao', 'pir', 'pyr', 'lan', 'lam', 'wyn',
    'win', 'pis', 'wim', 'lak', 'alc', 'lay', 'lai', 'lah', 'lag', 'lad', 'pit',
    'lac', 'piu', 'pix', 'pyx', 'lab', 'oka', 'oke', 'oki', 'ald', 'abt', 'kui',
    'ale', 'kue', 'kua', 'abu', 'ksi', 'kru', 'krs', 'neg', 'pkg', 'pks', 'pkt',
    'nef', 'kra', 'nus', 'kph', 'kpc', 'kou', 'kos', 'kor', 'kop', 'alf', 'kon',
    'kol', 'alg', 'koi', 'kob', 'koa', 'ola', 'wig', 'old', 'nee', 'aly', 'kln',
    'ned', 'kyu', 'kit', 'wye', 'kip', 'kin', 'kim', 'kyl', 'kil', 'alk', 'kif',
    'kye', 'kie', 'kyd', 'kid', 'wid', 'abv', 'ole', 'khu', 'khi', 'kha', 'kgr',
    'kgf', 'nut', 'kex', 'all', 'ket', 'zip', 'neb', 'ker', 'kep', 'whs', 'whr',
    'ken', 'key', 'keg', 'kef', 'kee', 'ked', 'keb', 'kea', 'nea', 'nos', 'kaw',
    'who', 'kat', 'kas', 'kan', 'kam', 'kal', 'kaj', 'kay', 'kai', 'kaf', 'kae',
    'kab', 'not', 'nco', 'juv', 'jut', 'plf', 'pli', 'ply', 'jus', 'jur', 'aln',
    'jun', 'alo', 'jug', 'alp', 'jud', 'nbg', 'oad', 'olm', 'naw', 'jow', 'jot',
    'jos', 'als', 'jon', 'alt', 'joy', 'plu', 'jog', 'joe', 'job', 'olp', 'jnt',
    'jnd', 'jms', 'jin', 'jim', 'jig', 'jib', 'nav', 'oaf', 'jew', 'jeu', 'jet',
    'jer', 'jen', 'jem', 'alw', 'nat', 'ama', 'jeg', 'jef', 'jee', 'jed', 'jct',
    'jcl', 'jaw', 'jat', 'jar', 'jap', 'jan', 'jam', 'amb', 'jak', 'jay', 'jai',
    'jah', 'why', 'whf', 'jag', 'jad', 'oms', 'pmk', 'pmt', 'oak', 'poa', 'pob',
    'jab', 'ona', 'acc', 'one', 'iwa', 'nar', 'ivy', 'ive', 'iva', 'oni', 'yus',
    'yup', 'yun', 'yum', 'yuk', 'yuh', 'yug', 'iud', 'its', 'ito', 'pod', 'ame',
    'itd', 'ita', 'ony', 'nap', 'isz', 'ist', 'poe', 'poh', 'poi', 'poy', 'pol',
    'iso', 'isn', 'ism', 'isl', 'ish', 'ise', 'ono', 'nan', 'yrs', 'ami', 'amy',
    'irs', 'irk', 'pom', 'ire', 'ira', 'nam', 'nak', 'iqs', 'zig', 'ips', 'ipr',
    'ipm', 'ipl', 'iph', 'yox', 'yow', 'you', 'iou', 'yot', 'ios', 'yor', 'yon',
    'ion', 'yom', 'yok', 'yoy', 'yoi', 'iof', 'yoe', 'wha', 'zho', 'ons', 'nay',
    'pon', 'yod', 'yob', 'nag', 'naf', 'pop', 'wet', 'inv', 'por', 'pos', 'wes',
    'pot', 'pow', 'pox', 'poz', 'nae', 'ppa', 'ppb', 'ppd', 'pph', 'ppi', 'ppl',
    'ppm', 'ppr', 'pps', 'ppt', 'nad', 'ont', 'pre', 'amp', 'wer', 'int', 'prf',
    'pry', 'wen', 'wem', 'prn', 'pro', 'ins', 'ino', 'inn', 'ink', 'ing', 'inf',
    'wey', 'wei', 'prp', 'prs', 'wef', 'zer', 'psf', 'psi', 'pst', 'psw', 'zep',
    'pta', 'pte', 'ptg', 'pty', 'ptp', 'amt', 'pts', 'ptt', 'nab', 'pua', 'amu',
    'pub', 'pud', 'pug', 'naa', 'ana', 'puy', 'pul', 'ind', 'pun', 'wee', 'pup',
    'pur', 'wed', 'pus', 'put', 'pvt', 'pwr', 'web', 'pwt', 'oam', 'qaf', 'qat',
    'oar', 'qed', 'inc', 'mxd', 'mwa', 'qid', 'abe', 'oat', 'mux', 'oof', 'qqv',
    'zen', 'qrs', 'ooh', 'mut', 'qtd', 'qty', 'qto', 'qtr', 'qts', 'zel', 'qua',
    'zek', 'oos', 'imu', 'que', 'qui', 'wea', 'zee', 'zed', 'oot', 'non', 'imp',
    'quo', 'opa', 'mus', 'ace', 'rab', 'wax', 'waw', 'imi', 'ima', 'ope', 'zea',
    'rad', 'anc', 'ill', 'ilk', 'rag', 'ile', 'ila', 'zax', 'ike', 'mun', 'ijo',
    'yis', 'yip', 'iyo', 'yin', 'iii', 'yid', 'zat', 'mum', 'ihs', 'and', 'ihp',
    'ihi', 'ign', 'ifs', 'iff', 'ife', 'opp', 'yez', 'yex', 'yew', 'yet', 'rah',
    'yes', 'yer', 'yep', 'ray', 'yeo', 'yen', 'ane', 'yeh', 'yee', 'yed', 'wat',
    'yea', 'ops', 'aal', 'yds', 'ids', 'ido', 'raj', 'ram', 'ide', 'ida', 'nou',
    'ora', 'icy', 'ran', 'ich', 'ice', 'zar', 'ibo', 'ibm', 'iba', 'orb', 'yaw',
    'yat', 'yas', 'was', 'yar', 'yap', 'yao', 'iao', 'yan', 'ian', 'yam', 'yak',
    'yay', 'yah', 'yad', 'orc', 'zap', 'mug', 'ord', 'hwt', 'hwy', 'hwa', 'mud',
    'hvy', 'zan', 'hut', 'hup', 'hun', 'rap', 'ani', 'any', 'hum', 'huk', 'hui',
    'huh', 'hug', 'hue', 'hud', 'hub', 'ore', 'hts', 'oba', 'hsi', 'mtx', 'hrs',
    'mts', 'mtn', 'mtg', 'hox', 'how', 'ras', 'hot', 'rat', 'war', 'hor', 'wap',
    'hop', 'hoo', 'raw', 'ann', 'hon', 'rax', 'mtd', 'rcd', 'rct', 'obb', 'mss',
    'rea', 'hom', 'reb', 'hol', 'hoy', 'hoi', 'hog', 'hoe', 'hod', 'hoc', 'wan',
    'hob', 'msl', 'hny', 'msg', 'hld', 'obe', 'hit', 'rec', 'his', 'hir', 'red',
    'ree', 'ref', 'ans', 'reg', 'reh', 'hyp', 'hip', 'ant', 'hin', 'rei', 'him',
    'hye', 'hie', 'rel', 'rem', 'ren', 'hyd', 'hid', 'hic', 'hia', 'mru', 'mrs',
    'hhd', 'hgt', 'zak', 'nom', 'rep', 'hex', 'hew', 'req', 'het', 'hes', 'res',
    'way', 'her', 'wah', 'hep', 'heo', 'hen', 'mph', 'ret', 'hem', 'wag', 'hel',
    'hey', 'waf', 'hei', 'heh', 'rev', 'wae', 'hee', 'hed', 'wad', 'wac', 'rew',
    'mpg', 'mpb', 'hcl', 'hcf', 'hcb', 'nol', 'wab', 'ach', 'zag', 'mow', 'vum',
    'haw', 'hav', 'hau', 'vug', 'orf', 'org', 'vss', 'mou', 'hat', 'ory', 'zad',
    'vox', 'has', 'rex', 'vow', 'mot', 'rfb', 'rfs', 'rfz', 'zac', 'orl', 'rha',
    'rhb', 'rhd', 'rhe', 'von', 'hap', 'hao', 'rho', 'han', 'ria', 'rya', 'rib',
    'ham', 'ric', 'hal', 'hak', 'vol', 'haj', 'rid', 'hay', 'hah', 'vog', 'voe',
    'vod', 'hag', 'haf', 'rie', 'rye', 'voc', 'mos', 'noy', 'rig', 'hae', 'viz',
    'had', 'hab', 'aby', 'xxx', 'xxv', 'guz', 'rik', 'guv', 'gut', 'gus', 'rim',
    'gur', 'gup', 'gun', 'gum', 'gul', 'rin', 'guy', 'vis', 'gue', 'gud', 'rio',
    'xxi', 'gtt', 'gte', 'gtd', 'gtc', 'noh', 'nog', 'grx', 'rip', 'grs', 'grr',
    'vip', 'gro', 'rit', 'gry', 'grf', 'riv', 'rix', 'gre', 'rld', 'rle', 'rly',
    'xvi', 'rms', 'nod', 'rnd', 'obi', 'vin', 'vim', 'rob', 'roc', 'rod', 'roe',
    'rog', 'vil', 'roi', 'roy', 'vii', 'rok', 'gra', 'obj', 'gps', 'gpm', 'gph',
    'gpd', 'vie', 'xyz', 'gox', 'gov', 'gou', 'rom', 'got', 'gos', 'gor', 'ron',
    'goo', 'vic', 'roo', 'gon', 'xix', 'aob', 'aor', 'gol', 'goy', 'goi', 'gog',
    'xiv', 'apa', 'god', 'gob', 'goa', 'xis', 'gnu', 'gns', 'ape', 'acy', 'ors',
    'ros', 'aph', 'glt', 'rot', 'via', 'ort', 'mor', 'vex', 'gld', 'glb', 'vet',
    'row', 'apl', 'mop', 'git', 'gis', 'rox', 'rpm', 'rps', 'rpt', 'nob', 'osc',
    'rte', 'rti', 'rtw', 'rua', 'rub', 'gyp', 'gip', 'gio', 'rud', 'gyn', 'gin',
    'rue', 'gym', 'gim', 'rug', 'gil', 'gig', 'gif', 'gye', 'gie', 'gid', 'gib',
    'moo', 'rum', 'ghi', 'ggr', 'gez', 'get', 'ges', 'run', 'ger', 'app', 'rus',
    'rut', 'geo', 'rux', 'rwd', 'rwy', 'ose', 'ack', 'saa', 'sab', 'sac', 'gen',
    'gem', 'gel', 'gey', 'gee', 'ged', 'geb', 'osi', 'gds', 'noa', 'ver', 'gcd',
    'sad', 'gaz', 'gaw', 'gau', 'gat', 'sae', 'sag', 'sah', 'sai', 'say', 'gas',
    'apr', 'saj', 'sak', 'apt', 'gar', 'gap', 'apx', 'otc', 'sal', 'gan', 'gam',
    'oto', 'ara', 'gal', 'gaj', 'gay', 'gag', 'gae', 'gad', 'gab', 'oud', 'ouf',
    'oui', 'fwd', 'our', 'out', 'sam', 'fut', 'arb', 'fur', 'san', 'fun', 'fum',
    'vel', 'fug', 'fud', 'fub', 'xii', 'arc', 'fth', 'nov', 'mon', 'frt', 'frs',
    'vei', 'sao', 'sap', 'fro', 'veg', 'vee', 'fry', 'sar', 'mom', 'mol', 'moy',
    'vax', 'vaw', 'vav', 'vau', 'vat', 'sat', 'fra', 'moi', 'fps', 'fpm', 'mog',
    'fox', 'fow', 'vas', 'fou', 'fot', 'sau', 'sav', 'saw', 'sax', 'moe', 'mod',
    'for', 'fop', 'foo', 'fon', 'are', 'fol', 'var', 'foy', 'foh', 'fog', 'foe',
    'fod', 'fob', 'moc', 'xed', 'fmt', 'mob', 'arf', 'arg', 'scf', 'sch', 'flu',
    'sci', 'flo', 'fll', 'fly', 'ary', 'fld', 'flb', 'now', 'fiz', 'fix', 'fit',
    'van', 'fir', 'ark', 'fip', 'arm', 'fin', 'scr', 'fil', 'fig', 'fie', 'fid',
    'arn', 'fib', 'aro', 'xcl', 'nox', 'fgn', 'xat', 'ffa', 'moa', 'fez', 'few',
    'feu', 'fet', 'sct', 'arr', 'fer', 'fen', 'fem', 'aam', 'sds', 'mna', 'sea',
    'fey', 'fei', 'feh', 'fee', 'fed', 'fec', 'ars', 'nix', 'fcs', 'fcp', 'fcy',
    'mmf', 'fbi', 'obl', 'fax', 'art', 'sec', 'fat', 'fas', 'val', 'vai', 'far',
    'faq', 'sed', 'fan', 'fam', 'see', 'vag', 'fay', 'fag', 'fae', 'vac', 'fad',
    'mlx', 'abl', 'mkt', 'seg', 'fac', 'aru', 'fab', 'mks', 'nit', 'sei', 'sey',
    'arx', 'nis', 'asa', 'sel', 'asb', 'sem', 'ext', 'exr', 'sen', 'uva', 'utu',
    'uts', 'sep', 'seq', 'exp', 'ser', 'uti', 'ase', 'asg', 'ash', 'set', 'sew',
    'ute', 'sex', 'mix', 'ewe', 'wut', 'evg', 'wus', 'sfm', 'sfz', 'uta', 'mit',
    'wur', 'usw', 'eve', 'sgd', 'wup', 'sha', 'eva', 'ask', 'ova', 'asp', 'usu',
    'ust', 'ety', 'she', 'eth', 'etc', 'eta', 'wun', 'esu', 'ush', 'est', 'ess',
    'use', 'esq', 'esp', 'ese', 'esd', 'esc', 'wud', 'ass', 'usa', 'obs', 'ers',
    'err', 'ern', 'erk', 'uru', 'shh', 'shi', 'shy', 'urs', 'erg', 'erf', 'ere',
    'erd', 'era', 'nip', 'abn', 'sho', 'uro', 'shp', 'shr', 'urn', 'epi', 'sht',
    'shu', 'ast', 'epa', 'act', 'eos', 'eon', 'eom', 'eof', 'mis', 'mir', 'sia',
    'env', 'sib', 'uri', 'sic', 'sid', 'urf', 'syd', 'sie', 'sye', 'sig', 'ens',
    'enl', 'ure', 'urd', 'sil', 'syl', 'urb', 'eng', 'sim', 'sym', 'end', 'sin',
    'syn', 'wro', 'ata', 'enc', 'min', 'emu', 'ems', 'emp', 'emm', 'ate', 'emf',
    'eme', 'ura', 'mym', 'sip', 'sir', 'syr', 'sis', 'mim', 'elt', 'els', 'elm',
    'ell', 'elk', 'sit', 'ati', 'eli', 'elf', 'atm', 'six', 'mil', 'ski', 'sky',
    'eld', 'elb', 'ela', 'myg', 'eke', 'att', 'eyr', 'eir', 'eyn', 'eyl', 'eye',
    'mig', 'wry', 'ego', 'egg', 'nim', 'eft', 'efs', 'owd', 'efl', 'sla', 'eff',
    'owe', 'eer', 'een', 'eel', 'owk', 'eds', 'edp', 'edo', 'ups', 'edh', 'owl',
    'ecu', 'sld', 'eco', 'sly', 'aud', 'ecb', 'own', 'ebb', 'eau', 'eat', 'auf',
    'aug', 'ear', 'ean', 'eam', 'ead', 'nil', 'ada', 'dzo', 'owt', 'aah', 'dwt',
    'dux', 'auh', 'auk', 'aul', 'upo', 'aum', 'dur', 'dup', 'duo', 'dun', 'dum',
    'dui', 'dug', 'due', 'dud', 'aus', 'duc', 'dub', 'mid', 'dtd', 'oxy', 'dsr',
    'dsp', 'abo', 'slt', 'dry', 'ozs', 'sma', 'obv', 'dpt', 'nig', 'doz', 'dow',
    'dot', 'dos', 'sml', 'pac', 'dor', 'dop', 'doo', 'don', 'dom', 'adc', 'dol',
    'doh', 'dog', 'doe', 'dod', 'doc', 'dob', 'doa', 'pad', 'add', 'pah', 'aux',
    'dlr', 'pay', 'dks', 'dkm', 'dkl', 'dkg', 'pal', 'myc', 'dix', 'ade', 'ava',
    'sny', 'div', 'ave', 'dit', 'mib', 'avg', 'sob', 'soc', 'sod', 'soe', 'sog',
    'soh', 'soy', 'sok', 'sol', 'avn', 'avo', 'son', 'mya', 'awa', 'sop', 'awd',
    'awe', 'sos', 'awk', 'sot', 'awl', 'awm', 'awn', 'sou', 'mia', 'axe', 'sov',
    'sow', 'sox', 'nye', 'spa', 'nid', 'dys', 'dis', 'dir', 'azo', 'dip', 'spy',
    'dyn', 'din', 'mhz', 'mho', 'baa', 'dim', 'bab', 'dil', 'dig', 'spl', 'dif',
    'dye', 'die', 'did', 'dib', 'bac', 'spp', 'dia', 'mhg', 'aas', 'dhu', 'dha',
    'mgt', 'dft', 'sps', 'spt', 'dex', 'dew', 'mgr', 'sqd', 'sqq', 'dev', 'det',
    'mgd', 'sri', 'oca', 'ssi', 'ssp', 'ssu', 'mfr', 'sta', 'des', 'der', 'std',
    'dep', 'bad', 'den', 'stg', 'sty', 'bae', 'dem', 'stk', 'bag', 'stm', 'del',
    'dey', 'dei', 'bah', 'deg', 'bai', 'bay', 'str', 'def', 'dee', 'stu', 'dec',
    'deb', 'mfg', 'bal', 'sub', 'dea', 'mfd', 'ddt', 'zoo', 'dcb', 'dca', 'mew',
    'dbl', 'mev', 'daw', 'dau', 'dat', 'das', 'dar', 'dap', 'dao', 'dan', 'dam',
    'dal', 'dak', 'day', 'dah', 'dag', 'dae', 'dad', 'dab', 'meu', 'nib', 'cwt',
    'cwo', 'cwm', 'wpm', 'cut', 'cur', 'cup', 'bam', 'cun', 'ban', 'cum', 'cul',
    'cuj', 'cue', 'cud', 'cub', 'wow', 'cts', 'ctr', 'cto', 'ctn', 'ctg', 'ctf',
    'cte', 'wot', 'csw', 'cst', 'csp', 'csk', 'csi', 'csc', 'pam', 'cru', 'crs',
    'cro', 'crl', 'sud', 'sue', 'suf', 'sui', 'suk', 'cry', 'bap', 'sum', 'bar',
    'cre', 'crc', 'sun', 'wos', 'pan', 'cpu', 'cpt', 'cps', 'cpo', 'cpm', 'cpl',
    'cpi', 'cpd', 'met', 'coz', 'cox', 'sup', 'cow', 'suq', 'sur', 'sus', 'suu',
    'suz', 'pap', 'svc', 'ady', 'swa', 'cot', 'swy', 'cos', 'par', 'mes', 'taa',
    'tab', 'aaa', 'cor', 'tad', 'tae', 'tag', 'tai', 'tay', 'cop', 'bas', 'coo',
    'taj', 'tal', 'tam', 'tan', 'tao', 'tap', 'tar', 'tas', 'tat', 'tau', 'bat',
    'tav', 'taw', 'tax', 'uns', 'mer', 'tbs', 'meq', 'tch', 'tck', 'meo', 'tdr',
    'adj', 'tea', 'tec', 'ted', 'tee', 'tef', 'teg', 'tel', 'tem', 'con', 'ten',
    'ter', 'baw', 'tew', 'tex', 'men', 'bbl', 'bbs', 'bcd', 'bcf', 'bch', 'mem',
    'bde', 'com', 'tez', 'tfr', 'mel', 'bdl', 'bds', 'adm', 'bea', 'tgn', 'tgt',
    'pas', 'tha', 'the', 'col', 'thy', 'coy', 'cog', 'tho', 'coe', 'cod', 'cob',
    'bec', 'meg', 'cml', 'cmd', 'mee', 'clr', 'pat', 'tib', 'clo', 'clk', 'tic',
    'bed', 'tid', 'cly', 'cli', 'tie', 'tye', 'tig', 'tyg', 'til', 'tim', 'med',
    'ckw', 'ado', 'civ', 'tin', 'cit', 'bee', 'cis', 'tip', 'typ', 'tyr', 'tis',
    'tit', 'tyt', 'cir', 'cyp', 'bef', 'tiu', 'tji', 'mea', 'tkt', 'tln', 'tlo',
    'tlr', 'byp', 'tmh', 'aba', 'tng', 'tnt', 'mcg', 'toa', 'tob', 'cyl', 'cig',
    'cif', 'cie', 'beg', 'cid', 'tod', 'toe', 'tog', 'toi', 'toy', 'cyc', 'tol',
    'cia', 'mcf', 'tom', 'chs', 'ton', 'too', 'top', 'bey', 'tor', 'tos', 'bel',
    'tot', 'cho', 'chn', 'chm', 'tou', 'tov', 'tow', 'tox', 'nth', 'tpd', 'tph',
    'tpi', 'tpk', 'tpm', 'tps', 'mbd', 'tra', 'chi', 'chg', 'che', 'trf', 'tri',
    'try', 'ben', 'cha', 'och', 'cgs', 'cgm', 'max', 'cfs', 'cfm', 'cfi', 'cfh',
    'cfd', 'maw', 'cep', 'cen', 'cee', 'wop', 'cdr', 'cdg', 'cdf', 'mau', 'ccw',
    'unp', 'ccm', 'adp', 'pau', 'caw', 'cav', 'trp', 'trs', 'trt', 'pav', 'tsi',
    'cat', 'tsk', 'tsp', 'tss', 'tst', 'tty', 'ads', 'ber', 'tua', 'tub', 'tue',
    'tug', 'tui', 'tuy', 'tum', 'tun', 'tup', 'tur', 'unn', 'bes', 'car', 'tut',
    'cap', 'tux', 'mat', 'twa', 'twi', 'can', 'two', 'twp', 'paw', 'txt', 'pax',
    'ubc', 'ubi', 'cam', 'pbx', 'uca', 'abp', 'udi', 'udo', 'uds', 'ufo', 'ufs',
    'pcf', 'ugh', 'ugt', 'pci', 'uhs', 'pcm', 'uit', 'uji', 'uke', 'ula', 'ule',
    'ull', 'ult', 'ulu', 'pct', 'bet', 'ume', 'umm', 'ump', 'cal', 'cay', 'cai',
    'cag', 'umu', 'abr', 'una', 'caf', 'cad', 'cab', 'pdl', 'pdn', 'pdq', 'bxs',
    'new', 'bvt', 'pea', 'buz', 'unb', 'but', 'bus', 'bur', 'mas', 'adv', 'bun',
    'bhd', 'bum', 'bhp', 'bul', 'ped', 'mar', 'buy', 'bug', 'bud', 'unc', 'bib',
    'bub', 'map', 'btu', 'btl', 'mao', 'bsh', 'bsf', 'pee', 'brr', 'bro', 'brl',
    'bid', 'bra', 'adz', 'bpt', 'bye', 'bps', 'bpi', 'ock', 'box', 'bow', 'big',
    'bot', 'bos', 'bor', 'bop', 'boo', 'bon', 'bom', 'bol', 'boy', 'boh', 'bog',
    'unl', 'boe', 'bod', 'boc', 'bob', 'boa', 'peg', 'bnf', 'peh', 'man', 'bim',
    'bls', 'ung', 'blo', 'blk', 'bin', 'bld', 'bio', 'woo', 'bkt', 'bks', 'bkg',
    'mam', 'biz', 'bit', 'uni', 'bys', 'bis', 'opt'
}

return w0, w1, w2, w3, w4
