w0 = {
    'å', '∫', 'ç', '∂', '´', 'ƒ', '©', '˙', 'ˆ', '∆', '˚', '¬',
    'µ', '˜', 'ø', 'π', 'œ', '®', 'ß', '†', '¨', '√', '∑', '≈',
    '¥', 'Í', '□', 'À', '�', '℮', '╤', 'ф', 'Ð', 'ñ', 'Ћ', 'Ç',
    'ƒ', 'Ё', 'ê', '№', 'Ä', '•', 'à', 'ü'
}
w1 = {
    '[Dwarlorahe]', '•0', '•3•', "'", '63636', '20', '0•', "'ƒ",
    '•Ð', 'ÇÍ', "2'", '00', '2Ð', '665G', '979', 'Ä2', '•Ç', '3À',
    'Ç•', 'ÇÇ', 'Ç1T', 'ƒb', 'Ç•AG3', 'Ç•ÇL', 'Í•1', 'Í•3',
    'ƒÇ12', 'ƒÇ•1', 'ƒÇ•2', 'Ç1b', 'Ç•ÇB', '№2', '№z',
    '•5', '22', 'you’re', 'À5G', 'Äà', "I'm", "'Ç", "'Ð"
}
w2 = {
    'zn', 'ok', 'ol', 'ac', 'ne', 'nd', 'nb', 'om', 'on', 'na', 'np', 'mw',
    'mv', 'op', 'or', 'mu', 'mt', 'ms', 'mr', 'mp', 'za', 'nr', 'xx', 'xw',
    'xu', 'xs', 'xr', 'os', 'ot', 'xi', 'xd', 'xc', 'mo', 'mn', 'mm', 'ml',
    'mk', 'ns', 'wu', 'wt', 'ws', 'ow', 'ad', 'ox', 'oz', 'nt', 'pa', 'my',
    'mi', 'mh', 'mg', 'mf', 'wr', 'me', 'md', 'mc', 'mb', 'pc', 'pd', 'pe',
    'ae', 'ma', 'nu', 'lx', 'af', 'lv', 'wo', 'wm', 'wl', 'wk', 'lu', 'lt',
    'ls', 'lr', 'lp', 'ag', 'pf', 'pg', 'ph', 'lo', 'ln', 'lm', 'll', 'pi',
    'ly', 'li', 'lh', 'lg', 'lf', 'ah', 'ai', 'ay', 'ak', 'le', 'ld', 'lc',
    'lb', 'al', 'la', 'zs', 'kw', 'kv', 'kt', 'pk', 'pl', 'kr', 'ko', 'kn',
    'km', 'kl', 'ky', 'ki', 'kg', 'wy', 'wi', 'kc', 'kb', 'ka', 'nv', 'ju',
    'jt', 'js', 'jr', 'jo', 'ji', 'jg', 'am', 'pm', 'po', 'ja', 'bk', 'ix',
    'iw', 'iv', 'yt', 'it', 'ys', 'is', 'yr', 'ir', 'iq', 'wh', 'wg', 'wf',
    'yo', 'io', 'pp', 'pq', 'pr', 'ps', 'pt', 'pu', 'an', 'ob', 'qe', 'qh',
    'qy', 'ql', 'qm', 'qn', 'qp', 'qr', 'qs', 'qt', 'qu', 'yn', 'in', 'we',
    'wd', 'wc', 'wb', 'qv', 'no', 'ra', 'ym', 'im', 'il', 'ik', 'yi', 'ii',
    'if', 'ye', 'ie', 'yd', 'id', 'ic', 'ib', 'ya', 'ia', 'nm', 'nl', 'hw',
    'hv', 'hu', 'ht', 'hs', 'hr', 'hq', 'hp', 'rc', 'ab', 're', 'ho', 'hm',
    'hl', 'hy', 'hi', 'hg', 'hf', 'aa', 'he', 'hd', 'hb', 'wa', 'nj', 'vv',
    'vu', 'vt', 'vs', 'vr', 'vp', 'rf', 'rg', 'rh', 'vo', 'vl', 'ha', 'oc',
    'gv', 'gu', 'gt', 'gs', 'rm', 'rn', 'ro', 'gr', 'gp', 'ao', 'ap', 'go',
    'gn', 'gm', 'vi', 'vg', 'gl', 'rs', 'rt', 'gi', 'ny', 'sa', 'ge', 'gd',
    'aq', 'ar', 'ga', 'ni', 'fz', 'fw', 'fv', 'fu', 'ft', 'fs', 'vd', 'vc',
    'vb', 'fr', 'fp', 'sb', 'sc', 'fo', 'fn', 'fm', 'fl', 'fy', 'fi', 'fg',
    'ff', 'sd', 'se', 'fe', 'fc', 'fb', 'va', 'ng', 'ux', 'fa', 'od', 'as',
    'ex', 'ew', 'sf', 'ut', 'sg', 'sh', 'eu', 'et', 'es', 'us', 'er', 'eq',
    'ep', 'eo', 'si', 'at', 'en', 'ur', 'em', 'sk', 'el', 'ey', 'eh', 'eg',
    'sl', 'ef', 'ee', 'ed', 'ec', 'ea', 'oe', 'dz', 'dx', 'du', 'dt', 'ds',
    'sm', 'dr', 'dp', 'up', 'sn', 'do', 'dn', 'dm', 'dl', 'dk', 'dj', 'av',
    'so', 'aw', 'ax', 'sp', 'az', 'of', 'ba', 'dy', 'di', 'dg', 'sq', 'sr',
    'ss', 'st', 'su', 'de', 'dd', 'dc', 'db', 'da', 'og', 'cv', 'cu', 'ct',
    'cs', 'cr', 'cq', 'cp', 'sv', 'sw', 'oh', 'ta', 'tb', 'tc', 'td', 'te',
    'bb', 'bd', 'tg', 'be', 'th', 'co', 'cm', 'ti', 'cl', 'ck', 'tk', 'tm',
    'tn', 'to', 'cy', 'tp', 'tr', 'ch', 'cg', 'cf', 'ce', 'cd', 'cc', 'cb',
    'ts', 'tu', 'tv', 'tx', 'oy', 'uc', 'ud', 'ug', 'uh', 'ui', 'um', 'un',
    'ca', 'zo', 'bz', 'bx', 'bv', 'bf', 'bg', 'bi', 'by', 'bu', 'bt', 'bs',
    'br', 'bp', 'bo', 'bn', 'bm', 'bl', 'rd'
}
w3 = {
    'aeq', 'aer', 'pen', 'mal', 'won', 'may', 'mah', 'pep', 'per', 'mag', 'mae',
    'wok', 'woy', 'aes', 'wog', 'mad', 'woe', 'aet', 'wod', 'mac', 'mab', 'oct',
    'noo', 'lxx', 'oda', 'wob', 'lwp', 'odd', 'lwo', 'lwm', 'afb', 'afd', 'lwl',
    'ode', 'aff', 'lux', 'lut', 'woa', 'ods', 'wmk', 'odz', 'nub', 'net', 'wjc',
    'lur', 'luo', 'wiz', 'lum', 'lui', 'lug', 'lue', 'lud', 'luc', 'lub', 'abs',
    'ltr', 'oer', 'lst', 'lsc', 'oes', 'abb', 'lpm', 'off', 'lox', 'pes', 'low',
    'lou', 'lot', 'aft', 'pet', 'lor', 'loq', 'lop', 'wit', 'loo', 'nep', 'aga',
    'loy', 'pew', 'log', 'lof', 'loe', 'lod', 'ofo', 'pfc', 'pfd', 'pfg', 'pfx',
    'oft', 'nul', 'age', 'loc', 'lob', 'loa', 'num', 'lnr', 'zod', 'ohm', 'llb',
    'oho', 'liz', 'wis', 'liv', 'phi', 'wir', 'lit', 'agy', 'lys', 'lis', 'lir',
    'liq', 'lip', 'pho', 'lyn', 'lin', 'ago', 'phr', 'lym', 'lim', 'pht', 'agr',
    'phu', 'ohs', 'pia', 'pya', 'lig', 'lif', 'pic', 'lye', 'lie', 'lid', 'lyc',
    'lib', 'agt', 'ohv', 'nor', 'lhd', 'lhb', 'oie', 'zoa', 'abc', 'lex', 'abd',
    'aha', 'lew', 'ahi', 'aho', 'ahs', 'aht', 'ahu', 'lev', 'pie', 'oii', 'oik',
    'pye', 'aid', 'aye', 'leu', 'pig', 'aik', 'let', 'ail', 'les', 'ler', 'aim',
    'pik', 'ain', 'air', 'pil', 'lep', 'leo', 'len', 'lek', 'ley', 'lei', 'pim',
    'leg', 'lee', 'ais', 'ays', 'led', 'pin', 'ait', 'ayu', 'aix', 'neo', 'aka',
    'lea', 'oil', 'ake', 'ldg', 'nek', 'lcm', 'lcd', 'lca', 'zit', 'lbw', 'lbs',
    'lbf', 'nei', 'laz', 'lax', 'law', 'ako', 'lav', 'aku', 'nun', 'ala', 'lat',
    'las', 'pip', 'lar', 'alb', 'lap', 'lao', 'pir', 'pyr', 'lan', 'lam', 'wyn',
    'win', 'pis', 'wim', 'lak', 'alc', 'lay', 'lai', 'lah', 'lag', 'lad', 'pit',
    'lac', 'piu', 'pix', 'pyx', 'lab', 'oka', 'oke', 'oki', 'ald', 'abt', 'kui',
    'ale', 'kue', 'kua', 'abu', 'ksi', 'kru', 'krs', 'neg', 'pkg', 'pks', 'pkt',
    'nef', 'kra', 'nus', 'kph', 'kpc', 'kou', 'kos', 'kor', 'kop', 'alf', 'kon',
    'kol', 'alg', 'koi', 'kob', 'koa', 'ola', 'wig', 'old', 'nee', 'aly', 'kln',
    'ned', 'kyu', 'kit', 'wye', 'kip', 'kin', 'kim', 'kyl', 'kil', 'alk', 'kif',
    'kye', 'kie', 'kyd', 'kid', 'wid', 'abv', 'ole', 'khu', 'khi', 'kha', 'kgr',
    'kgf', 'nut', 'kex', 'all', 'ket', 'zip', 'neb', 'ker', 'kep', 'whs', 'whr',
    'ken', 'key', 'keg', 'kef', 'kee', 'ked', 'keb', 'kea', 'nea', 'nos', 'kaw',
    'who', 'kat', 'kas', 'kan', 'kam', 'kal', 'kaj', 'kay', 'kai', 'kaf', 'kae',
    'kab', 'not', 'nco', 'juv', 'jut', 'plf', 'pli', 'ply', 'jus', 'jur', 'aln',
    'jun', 'alo', 'jug', 'alp', 'jud', 'nbg', 'oad', 'olm', 'naw', 'jow', 'jot',
    'jos', 'als', 'jon', 'alt', 'joy', 'plu', 'jog', 'joe', 'job', 'olp', 'jnt',
    'jnd', 'jms', 'jin', 'jim', 'jig', 'jib', 'nav', 'oaf', 'jew', 'jeu', 'jet',
    'jer', 'jen', 'jem', 'alw', 'nat', 'ama', 'jeg', 'jef', 'jee', 'jed', 'jct',
    'jcl', 'jaw', 'jat', 'jar', 'jap', 'jan', 'jam', 'amb', 'jak', 'jay', 'jai',
    'jah', 'why', 'whf', 'jag', 'jad', 'oms', 'pmk', 'pmt', 'oak', 'poa', 'pob',
    'jab', 'ona', 'acc', 'one', 'iwa', 'nar', 'ivy', 'ive', 'iva', 'oni', 'yus',
    'yup', 'yun', 'yum', 'yuk', 'yuh', 'yug', 'iud', 'its', 'ito', 'pod', 'ame',
    'itd', 'ita', 'ony', 'nap', 'isz', 'ist', 'poe', 'poh', 'poi', 'poy', 'pol',
    'iso', 'isn', 'ism', 'isl', 'ish', 'ise', 'ono', 'nan', 'yrs', 'ami', 'amy',
    'irs', 'irk', 'pom', 'ire', 'ira', 'nam', 'nak', 'iqs', 'zig', 'ips', 'ipr',
    'ipm', 'ipl', 'iph', 'yox', 'yow', 'you', 'iou', 'yot', 'ios', 'yor', 'yon',
    'ion', 'yom', 'yok', 'yoy', 'yoi', 'iof', 'yoe', 'wha', 'zho', 'ons', 'nay',
    'pon', 'yod', 'yob', 'nag', 'naf', 'pop', 'wet', 'inv', 'por', 'pos', 'wes',
    'pot', 'pow', 'pox', 'poz', 'nae'
}
w4 = {
    'kits', 'kith', 'kyte', 'kite', 'alif', 'mpbs', 'kist', 'kiss', 'wied',
    'kish', 'alii', 'nhan', 'kirn', 'kirk', 'widu', 'kiri', 'kips', 'kipe',
    'ngai', 'alin', 'kins', 'kino', 'kink', 'plak', 'plan', 'king', 'kine',
    'kind', 'kina', 'mozo', 'zags', 'kilt', 'kilp', 'kylo', 'kilo', 'kiln',
    'alit', 'kill', 'alix', 'kyle', 'moze', 'ored', 'kiku', 'moxo', 'kiki',
    'kyke', 'kike', 'kiyi', 'kiho', 'kifs', 'nump', 'kiev', 'kier', 'kiel',
    'kief', 'moxa', 'abos', 'kids', 'wyde', 'wide', 'mowt', 'mows', 'kick',
    'kiby', 'kibe', 'kyat', 'mown', 'kyar', 'plap', 'kyak', 'kyah', 'mowe',
    'next', 'khud', 'move', 'khot', 'khis', 'khir', 'alky', 'ores', 'khet',
    'khat', 'khar', 'khan', 'mout', 'newt', 'orfe', 'ache', 'kexy', 'abay',
    'moup', 'keup', 'ketu', 'keto', 'keta', 'moun', 'wick', 'kers', 'kero',
    'alle', 'kern', 'kerl', 'kerf', 'wych', 'wich', 'wice', 'kerb', 'plat',
    'moul', 'moue', 'whuz', 'moud', 'kept', 'keps', 'whup', 'whun', 'kepi',
    'news', 'kent', 'whud', 'kens', 'keno', 'kenn', 'kend', 'whse', 'achy',
    'mott', 'mots', 'kemp', 'kemb', 'kelt', 'kelp', 'kell', 'kelk', 'kele',
    'keld', 'keys', 'keir', 'ally', 'keid', 'orgy', 'kegs', 'abow', 'kefs',
    'abox', 'keet', 'kees', 'keep', 'keen', 'whop', 'keel', 'keek', 'keef',
    'zack', 'orig', 'keck', 'moth', 'keat', 'keas', 'keap', 'mote', 'allo',
    'kcal', 'zach', 'whoo', 'kbps', 'kbar', 'mota', 'kazi', 'norn', 'whom',
    'kavi', 'kava', 'whod', 'whoa', 'most', 'kats', 'katy', 'kath', 'kate',
    'plea', 'zuza', 'whiz', 'kasm', 'kasa', 'moss', 'kart', 'karo', 'karn',
    'karl', 'pleb', 'pled', 'kari', 'kapp', 'kaph', 'kapa', 'kaon', 'kant',
    'kans', 'kang', 'kane', 'kand', 'kana', 'oryx', 'whit', 'kami', 'kame',
    'kama', 'mosk', 'kalo', 'kali', 'alls', 'kale', 'kala', 'mose', 'kaki',
    'kaka', 'nunc', 'kays', 'kayo', 'kain', 'kail', 'kaik', 'kaif', 'kaid',
    'orle', 'nevo', 'alma', 'kahu', 'kaha', 'kagu', 'kago', 'kafa', 'morw',
    'kaes', 'nevi', 'kadu', 'alme', 'kadi', 'kabs', 'neve', 'kaas', 'orly',
    'ocht', 'juza', 'plew', 'plex', 'nuns', 'juts', 'jute', 'xxiv', 'xxii',
    'neut', 'nupe', 'just', 'nurl', 'plie', 'alms', 'jury', 'juri', 'jure',
    'plim', 'jura', 'xvii', 'jupe', 'nong', 'junt', 'juno', 'junk', 'june',
    'junc', 'odal', 'odax', 'jump', 'alod', 'july', 'aloe', 'jule', 'juke',
    'juju', 'juha', 'jugs', 'juga', 'xref', 'plod', 'judo', 'alop', 'ploy',
    'whys', 'judy', 'plop', 'alow', 'xray', 'jude', 'zone', 'juck', 'plot',
    'jube', 'juba', 'juan', 'xosa', 'orlo', 'xmas', 'nose', 'jozy', 'jows',
    'jowl', 'whir', 'odds', 'jovy', 'jove', 'jova', 'jour', 'plow', 'joul',
    'jouk', 'joug', 'jots', 'jota', 'nuts', 'joss', 'alps', 'josh', 'jose',
    'orna', 'joon', 'joom', 'mort', 'jook', 'joni', 'jong', 'xyst', 'also',
    'jolt', 'joll', 'odea', 'jole', 'joky', 'joke', 'joys', 'join', 'joie',
    'mors', 'odel', 'john', 'jogs', 'moro', 'joes', 'joel', 'joey', 'orra',
    'jodo', 'jocu', 'plud', 'plug', 'jock', 'joch', 'jobs', 'jobo', 'whip',
    'whyo', 'jobe', 'morn', 'joan', 'acid', 'abri', 'odes', 'morg', 'jive',
    'jiva', 'jiti', 'jism', 'jiri', 'jynx', 'jinx', 'jins', 'plum', 'jinn',
    'jink', 'jing', 'alto', 'jina', 'orth', 'jimp', 'xipe', 'jilt', 'jill',
    'alts', 'jigs', 'xint', 'jiff', 'jibs', 'jibi', 'alum', 'jibe', 'jibb',
    'more', 'jiao', 'mord', 'whin', 'jhvh', 'jhow', 'jger', 'xina', 'jews',
    'jewy', 'mora', 'jeux', 'odic', 'jets', 'jete', 'mops', 'jesu', 'jest',
    'jess', 'jert', 'alur', 'jerm', 'jerl', 'jerk', 'jere', 'mopy', 'jeon',
    'whim', 'moph', 'mope', 'jell', 'odyl', 'moot', 'acyl', 'jehu', 'moos',
    'jeff', 'jefe', 'orts', 'jeez', 'jees', 'jeer', 'amah', 'amay', 'jeep',
    'jeel', 'jeed', 'moor', 'moop', 'amal', 'jear', 'jean', 'jctn', 'odin',
    'osar', 'jazz', 'jazy', 'jaws', 'jawp', 'jawn', 'jawy', 'odor', 'java',
    'jaup', 'jaun', 'jauk', 'jato', 'jati', 'moon', 'amar', 'jasz', 'jass',
    'jasp', 'whig', 'jasy', 'jars', 'jarp', 'jarl', 'jark', 'plup', 'plur',
    'jarg', 'amas', 'jara', 'mool', 'jape', 'plus', 'mood', 'jaob', 'jant',
    'jann', 'jank', 'jane', 'neum', 'jams', 'jami', 'jamb', 'jama', 'xylo',
    'jako', 'acis', 'amba', 'jake', 'neuk'
}
