let ear = `
A B K V G H l L m N R S T v W GO AND O E REGEN AN NO Y M V U NU WI TH KO RE VI r RUFF FAR HI ME MO ER m AD GOT Fa HAMER !@#$ MAN ROT SKIL
RUFT LAND THo LORD UD Od DA TI FORTHIS endIrv GOT Od RAs AS BO
U O E Y E E E Y Y E O E O Y Y E O Y O E O O O O Y U E Y Y Y Y Y Y Y O E
RE RE LO AN LO LO ME RE LO LO RE LO VE LO AN SE AN AN LO AN AN LO ME RE RE RE TI SE NE NE NE TI KO SE SE TI SE SE RU TI TI AN TI TI SE TI NE TI KO NE SE TI VA VA VA ME VA VE AN VA VE ME VA ME LO ME VE
KO VA VA VA VA ME VA LO VE VE VA KO KO LU KO KO KO SE RU KO LU KO LU SE LU RU ME LU LU LU KO KO LU NE RU RU RU RE RE AN LO LO RE VA RE AN RE RE AN VA LO LO SE AN RE LO RE LO AN VA LO LO AN TI NE SE NE
SE SE LU TI SE TI TI SE RU TI TI RE TI NE SE NE NE NE RU NE NE TI ME VE VA ME VE ME RE ME ME VA VA VE LO ME ME LU VA ME VE ME ME VE AN VE VA VE KO RU KO RU LU LU TI LU RU LU KO RU NE RU RU VA RU KO RU
LU RU KO NE LU KO RU LO AN RE RE LO AN VA RE RE LO LO AN ME RE AN TI AN LO LO AN RE RE VA RE AN RE TI SE TI SE SE TI LU NE TI TI TI NE RU SE NE LO NE NE SE SE SE SE RU TI SE TI VA VA ME VA VE ME LO VE
VE VA VA VA AN VA ME KO ME VA VA ME VA VA AN VA VE ME KO KO LU RU RU LU NE RU KO KO RU RU SE RU KO ME RU RU RU LU RU RU NE LU KO RU LO LO LO LO LO RE VE AN RE RE AN LO VA LO LO SE LO AN RE AN LO LO ME
RE AN LO NE NE SE NE SE SE KO TI SE SE NE SE LU SE TI RE NE NE NE NE NE TI RU NE TI SE VA ME ME VA ME VA LO ME VA ME ME VA RE VA VE KO VE VE VA ME VA VE LO VE VA ME SE TI SE TI SE NE KO SE TI TI TI SE
LU NE NE AN TI SE SE NE TI NE KO SE TI TI LO AN LO AN LO LO ME LO RE RE RE RE VE LO LO NE RE LO AN AN AN RE VA LO RE RE TI TI SE NE NE SE KO NE NE TI SE SE KO NE TI AN TI SE SE TI NE TI RU NE NE NE ME
VE VE VE VE ME LO ME VE ME VE ME LO VA ME RU VE VE ME ME VE VA AN ME VE VE RU KO LU RU RU KO NE RU LU RU RU RU TI RU KO VE KO KO RU LU RU LU TI LU RU KO LO RE AN AN RE RE VE LO LO AN RE LO VA LO LO SE
AN RE LO LO AN AN VE LO LO AN SE SE TI NE TI SE KO NE TI NE TI NE RU SE SE LO NE SE TI TI NE TI RU SE TI TI VE VE ME VE VA VA AN VA VE ME ME VA RE VA VA LU ME ME VA VA VE VE RE ME VE VE RU KO LU LU RU
KO TI KO RU KO LU KO SE KO LU ME LU LU RU KO LU KO SE RU RU KO AN LO AN LO RE LO ME RE AN AN RE LO VA LO RE TI AN LO AN RE LO RE VE AN RE LO SE TI TI NE SE SE KO TI SE NE TI SE LU TI SE LO NE TI SE SE
NE NE RU SE TI NE
GOL BUR NUD RAS LON BUR LON VIL HIR LON VER VER LON HIR BOR RAS MOD GOL MOD WOS RAS BOR VER RAS WOS VER WOS VIL HIR VER MOD BUR VER FAR HIR GOL BUR RAS VER MOD LON LON RAS NUD VER BUR VER NUD BOR MOD RAS
BOR GOL NUD GOL MOD VER WOS VER HIR VIL GOL BUR LON GOL BUR BUR ASH WOS VER VER HIR MOD BOR HIR WOS WOS WOS ASH ASH RAS ASH VER LON VER FAR LON NUD VER GOL LON FAR VIL GOL VIL GOL FAR BOR ASH VIL FAR VIL
MOD VER WOS WOS LON GOL HIR HIR BUR MOD LON BUR HIR GOL VER VER BOR ASH VIL HIR HIR HIR GOL BOR RAS LON FAR BUR VIL RAS BOR BOR HIR MOD VIL VIL HIR RAS LON RAS FAR VER RAS FAR RAS NUD NUD BOR BOR NUD LON
FAR BOR RAS NUD GOL ASH GOL NUD GOL MOD ASH MOD NUD FAR FAR HIR WOS HIR RAS VER BUR LON GOL GOL LON VER MOD VER WOS HIR HIR HIR FAR BUR RAS ASH BUR FAR LON BOR WOS LON NUD HIR BUR MOD WOS ASH GOL FAR LON
NUD HIR BOR BOR BUR ASH FAR VIL VER FAR FAR LON ASH VIL RAS VER RAS VIL BUR GOL FAR LON WOS VER VIL VIL BOR FAR NUD BUR HIR VER GOL FAR NUD VIL BOR RAS VER BOR HIR ASH MOD HIR BOR BUR LON BUR BOR BOR FAR
MOD WOS NUD WOS NUD GOL GOL BUR BOR VER VER LON MOD BOR ASH VER BUR WOS GOL ASH VIL BUR FAR FAR HIR BOR WOS RAS WOS VIL BOR GOL VER VER BUR VER BUR LON VIL RAS ASH HIR NUD LON HIR LON WOS VER MOD NUD BOR
BUR BUR BUR BOR GOL ASH RAS BOR LON ASH VIL NUD WOS FAR ASH LON VER NUD NUD LON LON BUR NUD NUD BUR GOL ASH FAR NUD LON GOL VIL BOR LON FAR ASH NUD LON VER GOL RAS ASH WOS WOS FAR ASH RAS LON RAS NUD NUD
ASH ASH RAS LON FAR BOR VIL GOL HIR NUD NUD RAS VER NUD NUD VIL RAS HIR RAS NUD ASH NUD VER NUD ASH VIL VIL NUD MOD ASH RAS HIR VIL ASH LON WOS HIR RAS VIL WOS VER ASH GOL VIL RAS VER WOS FAR VIL HIR GOL
RAS GOL HIR VIL WOS VER RAS VER HIR HIR HIR WOS LON BOR BOR FAR GOL LON VER ASH GOL MOD GOL WOS ASH VIL BOR WOS WOS VIL LON FAR VIL VIL BOR FAR GOL ASH RAS FAR VIL WOS WOS RAS ASH MOD MOD BOR NUD MOD FAR
BOR ASH GOL ASH RAS RAS LON RAS FAR BUR WOS HIR NUD GOL VIL VIL VER VIL RAS NUD VIL LON VER NUD VIL RAS NUD LON NUD NUD MOD GOL MOD MOD GOL WOS WOS BUR HIR ASH WOS VER BOR ASH MOD LON WOS VIL RAS BOR BUR
MOD VIL BOR VIL HIR WOS BOR RAS FAR FAR MOD MOD WOS VIL HIR VER WOS GOL VER RAS HIR MOD BOR ASH NUD HIR BUR BOR ASH HIR VIL NUD GOL NUD FAR WOS ASH BUR VER LON MOD HIR GOL BUR GOL BOR WOS RAS MOD WOS MOD
NUD VIL HIR WOS WOS LON MOD NUD VER RAS BOR WOS LON VIL GOL LON MOD RAS RAS HIR WOS RAS NUD BOR ASH BUR BOR NUD BOR GOL LON GOL LON LON WOS HIR NUD HIR MOD NUD VIL BOR BUR VER GOL BUR MOD WOS VER HIR LON
FAR GOL VIL RAS BUR VIL VIL GOL RAS NUD GOL ASH GOL RAS BUR ASH GOL LON VER FAR BUR HIR VER WOS BOR VER FAR VIL HIR LON LON VIL ASH HIR LON VER HIR FAR VIL VER VIL WOS BOR FAR BOR MOD FAR ASH ASH VIL BOR
LON WOS RAS FAR NUD MOD NUD WOS HIR VIL NUD NUD MOD MOD MOD LON LON MOD WOS RAS NUD WOS RAS VIL HIR RAS BOR VER VER LON WOS WOS MOD LON WOS HIR BUR VER ASH FAR HIR WOS VER GOL BUR HIR GOL RAS LON HIR VIL
LON BUR GOL MOD BOR VER RAS VIL VER FAR WOS BUR RAS VIL ASH BOR VER FAR BOR MOD GOL VER RAS BUR FAR MOD HIR VER NUD GOL MOD BOR FAR NUD FAR VIL NUD NUD ASH NUD VIL VER VER RAS WOS HIR MOD BOR LON VIL VER
VER WOS LON BUR BOR HIR VER GOL BOR RAS VIL NUD VIL VER VIL LON BUR BOR BUR FAR HIR HIR VIL ASH FAR NUD VIL GOL RAS WOS BUR WOS VIL VER NUD BUR NUD MOD HIR HIR NUD VIL NUD FAR NUD RAS VER GOL NUD RAS BOR
MOD GOL GOL HIR VER BUR RAS GOL LON ASH NUD VIL BUR BUR ASH VIL VER ASH ASH BUR FAR ASH BOR BOR VER HIR VER NUD BOR NUD FAR VER GOL MOD GOL VIL BUR BUR FAR MOD RAS MOD BUR GOL BOR VIL HIR GOL WOS ASH BOR
RAS BOR BUR BOR LON WOS BUR FAR GOL FAR GOL VIL RAS HIR WOS HIR BOR ASH BUR VIL ASH NUD VER WOS ASH BOR RAS FAR LON GOL WOS VER BUR LON NUD LON LON ASH VER GOL HIR BOR RAS VIL FAR FAR ASH BUR WOS NUD VIL
MOD BOR BUR FAR NUD HIR LON ASH LON RAS VIL FAR ASH FAR HIR HIR BOR RAS FAR BUR VER HIR LON BOR MOD LON FAR HIR HIR HIR BOR VER FAR NUD GOL MOD GOL VER HIR ASH VER ASH ASH LON GOL ASH GOL VER FAR RAS BOR
VIL RAS LON LON NUD MOD FAR FAR HIR VIL BOR GOL RAS VER MOD VER BUR LON FAR GOL MOD NUD LON VER VIL NUD GOL MOD BOR WOS ASH VER VIL FAR HIR HIR FAR NUD WOS LON LON LON LON LON GOL VER WOS VIL LON VER VER
`
  .replace(/\r|\n/g, ' ')
  .trim()
  .split(' ')

let aly = [
  'Í',
  '□',
  'À',
  '�',
  '℮',
  '╤',
  'ф',
  'Ð',
  'ñ',
  'Ћ',
  'Ç',
  'ƒ',
  'Ё',
  'ê',
  '№',
  '•0',
  '•3•',
  "'",
  '2',
  '63636',
  '20',
  '0•',
  '3',
  'Ä',
  '•',
  '0',
  "'ƒ",
  '•Ð',
  'ÇÍ',
  "2'",
  '00',
  '2Ð',
  'à',
  '665G',
  '979',
  'Ä2',
  '•Ç',
  '3À',
  'Ç•',
  'ü',
  'ÇÇ',
  'Ç1T',
  'ƒb',
  'Ç•AG3',
  'Ç•ÇL',
  'Í•1',
  'Í•3',
  'ƒÇ12',
  'ƒÇ•1',
  'ƒÇ•2',
  'Ç1b',
  'Ç•ÇB',
  '№2',
  '№z',
  '•5',
  '22',
  '5565255',
  'you’re',
  'À5G',
  'Äà',
  "I'm",
  "'Ç",
  "'Ð"
]

function g(n) {
  return String.fromCharCode(
    n < 10 ? 48 + n : n < 36 ? 65 + n - 10 : 97 + n - 36
  )
}

for (let i = 0; i < 36; i++) aly.push(g(i))

for (let i = 10; i < 36; i++)
  for (let j = 10; j < 36; j++) aly.push(g(i) + g(j))

for (let i = 10; i < 36; i++)
  for (let j = 10; j < 36; j++)
    for (let k = 10; k < 36; k++) aly.push(g(i) + g(j) + g(k))

let dict = {}

ear.forEach((x, i) => {
  dict[x] = aly[i]
  // if (dict[x].indexOf(aly[i]) < 0 && dict[x].length < 2) dict[x].push(aly[i])
})

let fs = require('fs')

let s = ''
for (let k in dict) s += `${k}='${dict[k]}',`
fs.writeFileSync('./old/tmp', s, 'utf-8')
